#include <stdio.h>
#include <math.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"

#include "filter.h"
#include "audio_data.h"   // generated by Python script

static const char *TAG = "EQ_OFFLINE";


void app_main(void)
{
    const float fs = 48000.0f;   // should match your WAV sample rate

    // ---- EQ band design choices ----
    const float fc_low   = 100.0f;
    const float bw_low   = 120.0f;

    const float fc_mid   = 1000.0f;
    const float bw_mid   = 800.0f;

    const float fc_high  = 10000.0f;
    const float bw_high  = 4000.0f;

    // ---- EQ gains per band ----
    float gain_low  = 2.0f;
    float gain_mid  = 1.5f;
    float gain_high = 0.5f;

    // ---- Filter parameter structs ----
    PARAMS p_low = {
        .g   = 1.0f,
        .wc  = 2.0f * (float)M_PI * fc_low / fs,
        .wbw = 2.0f * (float)M_PI * bw_low,
        .T   = 1.0f / fs,
    };

    PARAMS p_mid = {
        .g   = 1.0f,
        .wc  = 2.0f * (float)M_PI * fc_mid / fs,
        .wbw = 2.0f * (float)M_PI * bw_mid,
        .T   = 1.0f / fs,
    };

    PARAMS p_high = {
        .g   = 0.2f,
        .wc  = 2.0f * (float)M_PI * fc_high / fs,
        .wbw = 2.0f * (float)M_PI * bw_high,
        .T   = 1.0f / fs,
    };

    float coeff_low[6], coeff_mid[6], coeff_high[6];

    float x_low_hist[3]  = {0};
    float y_low_hist[3]  = {0};

    float x_mid_hist[3]  = {0};
    float y_mid_hist[3]  = {0};

    float x_high_hist[3] = {0};
    float y_high_hist[3] = {0};

    filter_init(&p_low,  coeff_low);
    filter_init(&p_mid,  coeff_mid);
    filter_init(&p_high, coeff_high);

    ESP_LOGI(TAG, "Starting 3-band EQ over %d samples", AUDIO_NUM_SAMPLES);

    // ---------- PROCESS ----------
    for (int n = 0; n < AUDIO_NUM_SAMPLES; n++) {
        float x = audio_data[n];

        buffer_update(x, x_low_hist);
        buffer_update(x, x_mid_hist);
        buffer_update(x, x_high_hist);

        float y_low  = filter_update(coeff_low,  x_low_hist,  y_low_hist);
        float y_mid  = filter_update(coeff_mid,  x_mid_hist,  y_mid_hist);
        float y_high = filter_update(coeff_high, x_high_hist, y_high_hist);

        float y = gain_low  * y_low
                + gain_mid  * y_mid
                + gain_high * y_high;

        printf("S %.7f\n", y);
    }

    ESP_LOGI(TAG, "Done dumping samples");
}
